# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "curdbee"
  s.version = "0.0.10"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Lakshan Perera"]
  s.date = "2013-02-22"
  s.email = "lakshan@vesess.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "curdbee.gemspec",
    "examples/create_invoice_for_new_client.rb",
    "examples/list_invoices.rb",
    "lib/curdbee.rb",
    "lib/curdbee/base.rb",
    "lib/curdbee/client.rb",
    "lib/curdbee/config.rb",
    "lib/curdbee/error.rb",
    "lib/curdbee/estimate.rb",
    "lib/curdbee/invoice.rb",
    "lib/curdbee/invoiceable.rb",
    "lib/curdbee/item.rb",
    "lib/curdbee/parser.rb",
    "lib/curdbee/payment.rb",
    "lib/curdbee/recurring_profile.rb",
    "spec/client_spec.rb",
    "spec/estimate_spec.rb",
    "spec/fixtures/client.json",
    "spec/fixtures/clients.json",
    "spec/fixtures/customers.json",
    "spec/fixtures/estimate.json",
    "spec/fixtures/estimates.json",
    "spec/fixtures/invoice.json",
    "spec/fixtures/invoices.json",
    "spec/fixtures/item.json",
    "spec/fixtures/items.json",
    "spec/fixtures/new_client.json",
    "spec/fixtures/new_estimate.json",
    "spec/fixtures/new_invoice.json",
    "spec/fixtures/new_item.json",
    "spec/fixtures/new_payment.json",
    "spec/fixtures/new_recurring_profile.json",
    "spec/fixtures/payment.json",
    "spec/fixtures/payments.json",
    "spec/fixtures/recurring_profile.json",
    "spec/fixtures/recurring_profiles.json",
    "spec/invoice_spec.rb",
    "spec/item_spec.rb",
    "spec/payment_spec.rb",
    "spec/recurring_profile_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/fakeweb_stubs.rb"
  ]
  s.homepage = "http://github.com/vesess/curdbee"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Ruby wrapper for the CurdBee API"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, ["~> 0.9.0"])
      s.add_runtime_dependency(%q<hashie>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<crack>, [">= 0"])
    else
      s.add_dependency(%q<httparty>, ["~> 0.9.0"])
      s.add_dependency(%q<hashie>, ["> 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<crack>, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>, ["~> 0.9.0"])
    s.add_dependency(%q<hashie>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<crack>, [">= 0"])
  end
end

